### ISSUE TITLE
Netlify CMS still needs more work

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#16]
Before a stable release, I think Netlify CMS needs some changes:

- add docs
- make interacting with issues easier
- potential custom widgets?

**Comment by mistermantas** [comment]
There’s been enough changes to make Netlify CMS more usable, so I’ll be using this issue to document custom widgets and settings in Netlify CMS for v3.

**Comment by mistermantas** [comment]
Custom previews are currently being worked on. Only good thing I could do with widgets is maybe make adding dates & classes (ie faded) easier

**Comment by mistermantas** [comment]
**Implemented better preview and warning, if the end date is similar to the beginning.**

I mean, I can't change the logo yet (could only come up with this hack, which doesn't even really accomplish anything).

```css

    @keyframes logo {
      0% { opacity: 1; }
      50% { opacity: 1; }
      100% { opacity: 0; }
    }

    section svg[viewBox="0 0 182 47"] g {
      animation: logo 5s;
      opacity: 0;
    }

```

Then...

```js
entry.getIn(['data', 'affected']).forEach(function(tag) {
  h('span', tag)
})
```

...had this worked (returns `3`, not array of tags), tags would've been in the preview, yet alas.

Also, tried adding a widget (date/time tracking), which crashes the whole CMS —

```js
      // Pass the name of a registered control to reuse with a new widget preview.
      CMS.registerEditorComponent({
        id: "track",
        label: "Date Tracking",
        fields: [{name: 'id', label: 'Year-Month-Day 24Hour:Minutes'}],
        fromBlock: function(match) {
          return {
            time: match[0]
          };
        },
        toBlock: function(obj) {
          return '{{< track "' + obj.time + '" >}}';
        },
        toPreview: function(obj) {
          return (
            '<span class="color:#999">' + obj.time + '</span>'
          );
        }
      });

      // {{< track "2018-08-07 23:37:00" >}}
```
