### ISSUE TITLE
Respect timezone even in last modified date when `timeZone` was set

### ISSUE THREAD

**Issue by everpeace** [cstate/cstate#248]
**Is your feature request related to a problem? Please describe.**

I set timezone explicitly in `config.yaml` like:

```yaml
timeZone: Asia/Tokyo
params:
  dateFormat: January 2, 2006 at 3:04 PM MST
  shortDateFormat: 15:04 MST — Jan 2
  enableLastMod: true
```

Then, issue date was rendered in expected timezone (JST in this case). But, last modified date was not.

issue metadata:
```yaml
---
title: Sample Issue
date: 2022-10-27 01:00:00
...
```

rendered issue header:
![image](https://user-images.githubusercontent.com/608782/198499105-0c47974a-f2df-4569-87c2-49b7b67b5d26.png)

rendered issue footer:
![image](https://user-images.githubusercontent.com/608782/198498928-ffa110ea-2409-49e3-8c89-94d2711bea49.png)

**Describe the solution you'd like**

If cstate prioritized backward compatibility, I would introduce `forceUTCInLastMod: true|false (default is true)`.

Or, it would be fine just to remove `.UTC` part from:

https://github.com/cstate/cstate/blob/548fcb9e38409902e12d117c745297e7637a7e67/layouts/issues/single.html#L24

**Describe alternatives you've considered**

**Additional context**

none.
