### ISSUE TITLE
❓ Translation question

### ISSUE THREAD

**Issue by HighError** [cstate/cstate#289]
Hi, in what context is "in" used here?
It would be great to get example strings where this is used

```yaml
##
## v4.4
##

- id: in
  translation: in
- id: weeksAgo
  translation: " w"
- id: yearAgo
  translation: " year"
```
